### ISSUE TITLE
case-sensitivity?

### ISSUE THREAD

**Issue by lsloan** [jakesankey/PHP-RestServer-Class#1]
I read in Jake's blog that RestServer method names and request parameter keys are case-insensitive.  Is that an option that can be disabled?  I prefer to have those things case-sensitive.  Call it a tiny security measure, if you will.

**Comment by jakesankey** [comment]
Lance,

RestServer does not currently have any config options out of the box but it would be a simple change in the RestServer class to switch it to case sensitive. Near the beginning of the handle() method, it does a logical test against case insensitive array. I plan to add configurability to this tool at some point but in the mean time feel free to fork it on github and make the mods you need. 

Thanks for the inquiry,

Jake
