### ISSUE TITLE
How can I register multiple classes with the rest server?

### ISSUE THREAD

**Issue by imvision** [jakesankey/PHP-RestServer-Class#2]
Creating two instances of reset server and then calling handle for both seems like an option but then one instance will probably give error.

**Comment by jakesankey** [comment]
I had some time this evening and went ahead and implemented the feature you requested. You can now add multiple classes. Please take a look at the revised readme.

**Comment by imvision** [comment]
Thanks for taking the time to implement this thing. Now it is usable in production :)
